# Generated by Django 4.1.1 on 2022-09-30 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='doc_name',
            new_name='doctor_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='pat_email',
            new_name='patient_email',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='pat_name',
            new_name='patient_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='pat_phone',
            new_name='patient_phone',
        ),
    ]
