# Generated by Django 4.1.1 on 2022-09-30 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_rename_doc_name_booking_doctor_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='doctor_name',
            new_name='doc_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='patient_email',
            new_name='pat_email',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='patient_name',
            new_name='pat_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='patient_phone',
            new_name='pat_phone',
        ),
    ]
